repository:
  allow_auto_merge: true
  delete_branch_on_merge: true
  has_downloads: false
  has_issues: false
  has_projects: false
  has_wiki: false
  private: false
teams:
- name: ce-admins
  permission: admin
